import { ClerkProvider, UserButton } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Logo from "@/components/Logo";
import ThemeSwitcher from "@/components/ThemeSwitcher";
//import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={""}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav className="flex justify-between border-b px-4 py-2 h-[60px] items-center">
              <Logo />
              <div className="flex gap-4 items-end">
                <ThemeSwitcher />
                <UserButton afterSignOutUrl="/" />
              </div>
            </nav>
            <div className="p-10">
            {children}
           </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
